In [18]:
from sklearn.svm import SVC
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [19]:
x=np.array([[3,4],[1,4],[2,3],[6,-1],[7,-1],[5,-3]])
y=np.array([-1,-1,-1,1,1,1])


In [20]:
clf=SVC(C=1e5,kernel='linear')
clf.fit(x,y)


SVC(C=100000.0, kernel='linear')

In [21]:
print('w= ',clf.coef_)
print('b= ',clf.intercept_)
print('Indices of support vectors = ',clf.support_)
print('Support vectors = ',clf.support_vectors_)
print('Number of support vectors for each class = ',clf.n_support_)
print('Coefficients of the support vector in the decision function = ',np.abs(clf.dual_coef_))

w=  [[ 0.25 -0.25]]
b=  [-0.75]
Indices of support vectors =  [2 3]
Support vectors =  [[ 2.  3.]
 [ 6. -1.]]
Number of support vectors for each class =  [1 1]
Coefficients of the support vector in the decision function =  [[0.0625 0.0625]]


In [22]:
df=pd.read_csv("F://glass.csv")
print("dataset",df)

dataset           RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]


In [23]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
print(scaler.fit_transform(df))

[[ 0.87286765  0.28495326  1.25463857 ... -0.35287683 -0.5864509
  -0.84827468]
 [-0.24933347  0.59181718  0.63616803 ... -0.35287683 -0.5864509
  -0.84827468]
 [-0.72131806  0.14993314  0.60142249 ... -0.35287683 -0.5864509
  -0.84827468]
 ...
 [ 0.75404635  1.16872135 -1.86551055 ...  2.95320036 -0.5864509
   2.01047778]
 [-0.61239854  1.19327046 -1.86551055 ...  2.81208731 -0.5864509
   2.01047778]
 [-0.41436305  1.00915211 -1.86551055 ...  3.01367739 -0.5864509
   2.01047778]]


In [24]:
x=df.drop('Type',axis=1)
y=df.Type

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)


from sklearn import svm
ml=svm.SVC(kernel='linear')
ml.fit(x_train,y_train)


print(ml.support_vectors_)

[[ 1.51596 12.79     3.61    ...  8.07     0.       0.26   ]
 [ 1.51905 13.6      3.62    ...  8.76     0.       0.     ]
 [ 1.51755 12.71     3.42    ...  8.64     0.       0.     ]
 ...
 [ 1.52365 15.79     1.83    ...  8.61     1.68     0.     ]
 [ 1.51508 15.15     0.      ...  8.34     0.63     0.     ]
 [ 1.5164  14.37     0.      ...  9.45     0.54     0.     ]]


In [26]:
print(ml.n_support_)

[38 48 12  8  3  9]


In [27]:
y_pred=ml.predict(x_test)

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print("Accuracy Score",accuracy_score(y_test,y_pred))

print("Confusion Matrix",confusion_matrix(y_test,y_pred))

print("Classification Report",classification_report(y_test,y_pred))

Accuracy Score 0.5538461538461539
Confusion Matrix [[13 14  0  0  0  0]
 [ 3 15  0  0  0  0]
 [ 2  3  0  0  0  0]
 [ 0  2  0  2  0  0]
 [ 0  4  0  0  2  0]
 [ 0  1  0  0  0  4]]
Classification Report               precision    recall  f1-score   support

           1       0.72      0.48      0.58        27
           2       0.38      0.83      0.53        18
           3       0.00      0.00      0.00         5
           5       1.00      0.50      0.67         4
           6       1.00      0.33      0.50         6
           7       1.00      0.80      0.89         5

    accuracy                           0.55        65
   macro avg       0.68      0.49      0.53        65
weighted avg       0.64      0.55      0.54        65



E:\Python\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [28]:
model1=SVC(kernel='sigmoid')
model2=SVC(kernel='poly')
model3=SVC(kernel='rbf')

#With Different Kernels

model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

SVC()

In [29]:
ypred1=model1.predict(x_test)
ypred2=model2.predict(x_test)
ypred3=model3.predict(x_test)

print("Accuracy Score of kernel 1",accuracy_score(y_test,ypred1))

print("Accuracy Score of kernel 2",accuracy_score(y_test,ypred2))

print("Accuracy Score of kernel 3",accuracy_score(y_test,ypred3))

Accuracy Score of kernel 1 0.27692307692307694
Accuracy Score of kernel 2 0.27692307692307694
Accuracy Score of kernel 3 0.27692307692307694


In [30]:
#Array method of using different kernels

[{'kernel':['rbf'],'gamma':[1e-3,1e-4],
     'C':[1,10,100,1000]},
{'kernel':['linear'],'C':[1,10,100,1000]},
{'kernel':['poly'],'gamma':[1e-3,1e-4],'degree':[2,3,4]},
{'kernel':['sigmoid'],'C':[1,10,100,1000],'gamma':[1e-3,1e-4,1e-5]}]

[{'kernel': ['rbf'], 'gamma': [0.001, 0.0001], 'C': [1, 10, 100, 1000]},
 {'kernel': ['linear'], 'C': [1, 10, 100, 1000]},
 {'kernel': ['poly'], 'gamma': [0.001, 0.0001], 'degree': [2, 3, 4]},
 {'kernel': ['sigmoid'],
  'C': [1, 10, 100, 1000],
  'gamma': [0.001, 0.0001, 1e-05]}]

In [31]:
params_grid1=[{'kernel':['rbf']},
             {'kernel':['linear']},
             {'kernel':['poly']},
             {'kernel':['sigmoid']}]

In [32]:
from sklearn.model_selection import GridSearchCV
svm_model=GridSearchCV(SVC(),params_grid1,cv=5)
svm_model.fit(x_train,y_train)

E:\Python\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


GridSearchCV(cv=5, estimator=SVC(),
             param_grid=[{'kernel': ['rbf']}, {'kernel': ['linear']},
                         {'kernel': ['poly']}, {'kernel': ['sigmoid']}])

In [33]:
print('Best score for training data:',svm_model.best_score_,"\n")

#View the best parameters for the model found using grid search
print('Best C:',svm_model.best_estimator_.C,"\n")
print('Best Kernel:',svm_model.best_estimator_.kernel,"\n")
print('Best Gamma:',svm_model.best_estimator_.gamma,"\n")

final_model=svm_model.best_estimator_
Y_pred=final_model.predict(x_test)

Best score for training data: 0.6239080459770114 

Best C: 1.0 

Best Kernel: linear 

Best Gamma: scale 



In [34]:
print(accuracy_score(y_test,Y_pred))

0.5538461538461539
